server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.h2.Driver
    initialization-mode: always
    platform: mysql
    url: jdbc:h2:mem:marvel
    username: admin
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
